Genepop 4.7.0: Hardy-Weinberg test

File: pop19.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:41:53)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.7270  0.0136  -0.0172 -0.0172  94873 switches
qPh2        0.4062  0.0229   0.0122  0.0122  94921 switches

Normal ending
