Genepop 4.7.0: Hardy-Weinberg test

File: pop16.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:41:49)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.4607  0.0156   0.0054  0.0054  94987 switches
qPh2        0.9176  0.0092  -0.0393 -0.0393  94859 switches

Normal ending
