Genepop 4.7.0: Hardy-Weinberg test

File: pop10.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:41:42)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.2097  0.0131   0.0285  0.0285  94961 switches
qPh2        0.6349  0.0199  -0.0069 -0.0069  94897 switches

Normal ending
