Genepop 4.7.0: Hardy-Weinberg test

File: pop15.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:41:48)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.7764  0.0134  -0.0220 -0.0220  94959 switches
qPh2        0.2238  0.0186   0.0290  0.0290  94867 switches

Normal ending
