Genepop 4.7.0: Hardy-Weinberg test

File: pop28.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:42:03)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.6179  0.0152  -0.0075 -0.0075  94963 switches
qPh2        0.4826  0.0226   0.0061  0.0061  94870 switches

Normal ending
