Genepop 4.7.0: Hardy-Weinberg test

File: pop24.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:41:58)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.6973  0.0145  -0.0143 -0.0143  94926 switches
qPh2        0.8596  0.0126  -0.0300 -0.0301  94952 switches

Normal ending
