Genepop 4.7.0: Hardy-Weinberg test

File: pop25.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:42:00)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.7045  0.0141  -0.0152 -0.0152  94975 switches
qPh2        0.3915  0.0229   0.0136  0.0136  94907 switches

Normal ending
