Genepop 4.7.0: Hardy-Weinberg test

File: pop26.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:42:01)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.3511  0.0153   0.0146  0.0146  94877 switches
qPh2        0.5743  0.0216  -0.0017 -0.0017  94878 switches

Normal ending
