Genepop 4.7.0: Hardy-Weinberg test

File: pop32.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:42:08)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.1277  0.0110   0.0389  0.0389  94877 switches
qPh2        0.1781  0.0167   0.0341  0.0341  94940 switches

Normal ending
