Genepop 4.7.0: Hardy-Weinberg test

File: pop35.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:42:11)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.1050  0.0097   0.0415  0.0415  94987 switches
qPh2        0.6871  0.0186  -0.0115 -0.0116  94949 switches

Normal ending
