Genepop 4.7.0: Hardy-Weinberg test

File: pop30.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:42:05)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.7824  0.0130  -0.0226 -0.0226  94890 switches
qPh2        0.2290  0.0186   0.0283  0.0283  94897 switches

Normal ending
