Genepop 4.7.0: Hardy-Weinberg test

File: pop49.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:42:27)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.9100  0.0080  -0.0396 -0.0396  94955 switches
qPh2        0.9640  0.0055  -0.0514 -0.0514  94889 switches

Normal ending
