Genepop 4.7.0: Hardy-Weinberg test

File: pop43.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:42:20)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.6436  0.0159  -0.0095 -0.0095  94877 switches
qPh2        0.9601  0.0064  -0.0499 -0.0500  94878 switches

Normal ending
