Genepop 4.7.0: Hardy-Weinberg test

File: pop47.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:42:25)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.7658  0.0138  -0.0208 -0.0208  94933 switches
qPh2        0.7937  0.0152  -0.0217 -0.0217  94904 switches

Normal ending
