Genepop 4.7.0: Hardy-Weinberg test

File: pop48.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:42:26)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.9976  0.0010  -0.0811 -0.0811  94917 switches
qPh2        0.4265  0.0239   0.0106  0.0106  94936 switches

Normal ending
