Genepop 4.7.0: Hardy-Weinberg test

File: pop41.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:42:18)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.2079  0.0131   0.0284  0.0284  94953 switches
qPh2        0.5630  0.0210  -0.0008 -0.0008  94926 switches

Normal ending
