Genepop 4.7.0: Hardy-Weinberg test

File: pop45.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:42:23)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.9904  0.0023  -0.0681 -0.0681  94945 switches
qPh2        0.8080  0.0142  -0.0234 -0.0234  94867 switches

Normal ending
