Genepop 4.7.0: Hardy-Weinberg test

File: pop46.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:42:24)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.6414  0.0157  -0.0092 -0.0092  94873 switches
qPh2        0.7049  0.0175  -0.0131 -0.0131  94927 switches

Normal ending
