Genepop 4.7.0: Hardy-Weinberg test

File: pop59.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:42:39)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.1262  0.0109   0.0388  0.0388  94949 switches
qPh2        0.9826  0.0037  -0.0609 -0.0609  94926 switches

Normal ending
