Genepop 4.7.0: Hardy-Weinberg test

File: pop51.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:42:29)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.5466  0.0165  -0.0012 -0.0012  94911 switches
qPh2        0.6118  0.0201  -0.0052 -0.0052  94915 switches

Normal ending
