Genepop 4.7.0: Hardy-Weinberg test

File: pop57.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:42:36)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.4105  0.0153   0.0094  0.0094  94983 switches
qPh2        0.2545  0.0190   0.0259  0.0260  94914 switches

Normal ending
