Genepop 4.7.0: Hardy-Weinberg test

File: pop56.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:42:35)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.0155  0.0033   0.0681  0.0681  94937 switches
qPh2        0.8404  0.0132  -0.0272 -0.0272  94839 switches

Normal ending
