Genepop 4.7.0: Hardy-Weinberg test

File: pop64.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:42:44)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.4808  0.0148   0.0039  0.0039  94933 switches
qPh2        0.5622  0.0210  -0.0008 -0.0008  94913 switches

Normal ending
