Genepop 4.7.0: Hardy-Weinberg test

File: pop6.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:41:38)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.8711  0.0099  -0.0329 -0.0329  94933 switches
qPh2        0.3650  0.0218   0.0157  0.0157  94885 switches

Normal ending
