Genepop 4.7.0: Hardy-Weinberg test

File: pop66.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:42:47)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.2912  0.0137   0.0197  0.0198  94913 switches
qPh2        0.2259  0.0186   0.0284  0.0284  94935 switches

Normal ending
