Genepop 4.7.0: Hardy-Weinberg test

File: pop62.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:42:42)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.6741  0.0150  -0.0123 -0.0123  94933 switches
qPh2        0.6127  0.0196  -0.0050 -0.0050  94946 switches

Normal ending
