Genepop 4.7.0: Hardy-Weinberg test

File: pop65.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:42:45)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.9018  0.0084  -0.0378 -0.0378  94937 switches
qPh2        0.5556  0.0216  -0.0004 -0.0004  94893 switches

Normal ending
