Genepop 4.7.0: Hardy-Weinberg test

File: pop73.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:42:55)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.1640  0.0112   0.0331  0.0332  94939 switches
qPh2        0.5153  0.0218   0.0033  0.0033  94913 switches

Normal ending
