Genepop 4.7.0: Hardy-Weinberg test

File: pop76.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:42:58)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.0050  0.0016   0.0815  0.0815  94863 switches
qPh2        0.8583  0.0132  -0.0296 -0.0296  94936 switches

Normal ending
