Genepop 4.7.0: Hardy-Weinberg test

File: pop78.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:43:00)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.4753  0.0150   0.0038  0.0038  94919 switches
qPh2        0.9025  0.0108  -0.0367 -0.0367  94931 switches

Normal ending
