Genepop 4.7.0: Hardy-Weinberg test

File: pop7.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:41:39)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.1307  0.0109   0.0378  0.0378  94979 switches
qPh2        0.7376  0.0167  -0.0161 -0.0162  94895 switches

Normal ending
