Genepop 4.7.0: Hardy-Weinberg test

File: pop81.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:43:04)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.9733  0.0037  -0.0562 -0.0562  94851 switches
qPh2        0.1019  0.0133   0.0445  0.0445  94919 switches

Normal ending
