Genepop 4.7.0: Hardy-Weinberg test

File: pop82.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:43:05)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.6060  0.0152  -0.0063 -0.0063  94786 switches
qPh2        0.5743  0.0216  -0.0017 -0.0017  94924 switches

Normal ending
