Genepop 4.7.0: Hardy-Weinberg test

File: pop85.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:43:08)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.2802  0.0126   0.0209  0.0209  94722 switches
qPh2        0.9788  0.0041  -0.0581 -0.0581  94952 switches

Normal ending
