Genepop 4.7.0: Hardy-Weinberg test

File: pop88.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:43:12)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.4328  0.0133   0.0076  0.0076  94719 switches
qPh2        0.8739  0.0119  -0.0323 -0.0323  94883 switches

Normal ending
