Genepop 4.7.0: Hardy-Weinberg test

File: pop80.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:43:03)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.4096  0.0147   0.0096  0.0096  94870 switches
qPh2        0.5308  0.0221   0.0019  0.0019  94934 switches

Normal ending
