Genepop 4.7.0: Hardy-Weinberg test

File: pop83.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:43:06)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.3607  0.0146   0.0136  0.0137  94818 switches
qPh2        0.3394  0.0217   0.0178  0.0179  94934 switches

Normal ending
