Genepop 4.7.0: Hardy-Weinberg test

File: pop86.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:43:09)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.9400  0.0059  -0.0459 -0.0459  94680 switches
qPh2        0.6887  0.0188  -0.0117 -0.0117  94925 switches

Normal ending
