Genepop 4.7.0: Hardy-Weinberg test

File: pop99.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:43:24)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.2834  0.0119   0.0206  0.0206  94042 switches
qPh2        0.9816  0.0039  -0.0598 -0.0599  94937 switches

Normal ending
