Genepop 4.7.0: Hardy-Weinberg test

File: pop95.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:43:20)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.4587  0.0135   0.0055  0.0055  94045 switches
qPh2        0.6227  0.0202  -0.0058 -0.0058  94892 switches

Normal ending
