Genepop 4.7.0: Hardy-Weinberg test

File: pop97.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:43:22)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.5111  0.0140   0.0015  0.0015  93867 switches
qPh2        0.8493  0.0130  -0.0286 -0.0286  94913 switches

Normal ending
