Genepop 4.7.0: Hardy-Weinberg test

File: pop98.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:43:23)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.9920  0.0017  -0.0691 -0.0691  93967 switches
qPh2        0.4880  0.0225   0.0054  0.0054  94911 switches

Normal ending
