Genepop 4.7.0: Hardy-Weinberg test

File: pop90.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:43:14)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.4714  0.0143   0.0048  0.0048  94507 switches
qPh2        0.0589  0.0097   0.0526  0.0526  94937 switches

Normal ending
