Genepop 4.7.0: Hardy-Weinberg test

File: pop96.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:43:21)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.5349  0.0134  -0.0005 -0.0005  93963 switches
qPh2        0.1531  0.0165   0.0373  0.0373  94879 switches

Normal ending
