Genepop 4.7.0: Hardy-Weinberg test

File: pop20.txt (Outputted by simuPOP at Tue, 12 Jun 2018 13:07:14)

Number of populations detected:    1
Number of loci detected:           1


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-100000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.6016  0.0935  -0.0017 -0.0017  99610 switches

Normal ending
