Genepop 4.7.0: Hardy-Weinberg test

File: pop24.txt (Outputted by simuPOP at Tue, 12 Jun 2018 14:58:05)

Number of populations detected:    1
Number of loci detected:           1


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-100000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.3652  0.0838   0.0003  0.0003  99618 switches

Normal ending
