Genepop 4.7.0: Hardy-Weinberg test

File: pop0.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:40:12)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.9309  0.0067  -0.0437 -0.0437  94975 switches
qPh2        0.3365  0.0224   0.0185  0.0185  94924 switches

Normal ending
