Genepop 4.7.0: Hardy-Weinberg test

File: pop45.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:40:47)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.0000  0.0000   0.3144  0.3147  94931 switches
qPh2        0.0000  0.0000   0.3476  0.3479  94815 switches

Normal ending
