Genepop 4.7.0: Hardy-Weinberg test

File: pop62.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:41:00)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.0000  0.0000   0.3967  0.3970  94913 switches
qPh2        0.0000  0.0000   0.3562  0.3565  94921 switches

Normal ending
