Genepop 4.7.0: Hardy-Weinberg test

File: pop18.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:18:49)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.4893  0.0151   0.0033  0.0033  94899 switches
qPh2        0.7700  0.0156  -0.0190 -0.0190  94873 switches

Normal ending
