Genepop 4.7.0: Hardy-Weinberg test

File: pop1.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:18:48)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.6068  0.0157  -0.0066 -0.0066  94987 switches
qPh2        0.4489  0.0230   0.0085  0.0085  94921 switches

Normal ending
