Genepop 4.7.0: Hardy-Weinberg test

File: pop19.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:18:49)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.0294  0.0054   0.0602  0.0602  94929 switches
qPh2        0.0865  0.0115   0.0470  0.0470  94904 switches

Normal ending
