Genepop 4.7.0: Hardy-Weinberg test

File: pop24.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:18:50)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.7747  0.0125  -0.0221 -0.0221  94827 switches
qPh2        0.8088  0.0141  -0.0234 -0.0235  94839 switches

Normal ending
