Genepop 4.7.0: Hardy-Weinberg test

File: pop22.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:18:50)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.7935  0.0123  -0.0238 -0.0238  94867 switches
qPh2        0.7110  0.0173  -0.0135 -0.0136  94908 switches

Normal ending
