Genepop 4.7.0: Hardy-Weinberg test

File: pop2.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:18:48)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.2467  0.0139   0.0243  0.0244  94969 switches
qPh2        0.9595  0.0063  -0.0497 -0.0497  94908 switches

Normal ending
