Genepop 4.7.0: Hardy-Weinberg test

File: pop27.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:18:50)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.7168  0.0130  -0.0165 -0.0165  94881 switches
qPh2        0.2301  0.0185   0.0279  0.0279  94915 switches

Normal ending
