Genepop 4.7.0: Hardy-Weinberg test

File: pop25.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:18:50)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.2060  0.0122   0.0289  0.0289  94755 switches
qPh2        0.5340  0.0217   0.0017  0.0017  94880 switches

Normal ending
