Genepop 4.7.0: Hardy-Weinberg test

File: pop47.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:18:51)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.1672  0.0113   0.0336  0.0336  94813 switches
qPh2        0.8692  0.0119  -0.0311 -0.0312  94859 switches

Normal ending
