Genepop 4.7.0: Hardy-Weinberg test

File: pop45.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:18:51)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.3622  0.0144   0.0133  0.0133  94845 switches
qPh2        0.6047  0.0208  -0.0046 -0.0046  94909 switches

Normal ending
