Genepop 4.7.0: Hardy-Weinberg test

File: pop40.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:18:51)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.1285  0.0108   0.0384  0.0384  94818 switches
qPh2        0.5998  0.0215  -0.0038 -0.0038  94801 switches

Normal ending
