Genepop 4.7.0: Hardy-Weinberg test

File: pop42.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:18:51)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.9375  0.0059  -0.0450 -0.0450  94849 switches
qPh2        0.3421  0.0204   0.0176  0.0176  94841 switches

Normal ending
