Genepop 4.7.0: Hardy-Weinberg test

File: pop54.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:18:52)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.9273  0.0064  -0.0429 -0.0429  94846 switches
qPh2        0.2861  0.0201   0.0225  0.0225  94851 switches

Normal ending
