Genepop 4.7.0: Hardy-Weinberg test

File: pop59.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:18:52)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.0121  0.0028   0.0713  0.0714  94772 switches
qPh2        0.5719  0.0202  -0.0015 -0.0015  94853 switches

Normal ending
