Genepop 4.7.0: Hardy-Weinberg test

File: pop67.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:18:53)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.6122  0.0153  -0.0068 -0.0068  94905 switches
qPh2        0.0361  0.0074   0.0603  0.0604  94699 switches

Normal ending
