Genepop 4.7.0: Hardy-Weinberg test

File: pop62.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:18:52)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.6998  0.0138  -0.0146 -0.0146  94774 switches
qPh2        0.3841  0.0222   0.0141  0.0141  94854 switches

Normal ending
