Genepop 4.7.0: Hardy-Weinberg test

File: pop65.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:18:53)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.9661  0.0043  -0.0533 -0.0533  94927 switches
qPh2        0.0796  0.0116   0.0490  0.0490  94749 switches

Normal ending
