Genepop 4.7.0: Hardy-Weinberg test

File: pop68.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:18:53)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.3047  0.0148   0.0187  0.0187  94877 switches
qPh2        0.4091  0.0229   0.0120  0.0120  94609 switches

Normal ending
