Genepop 4.7.0: Hardy-Weinberg test

File: pop7.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:18:49)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.7508  0.0133  -0.0195 -0.0196  94929 switches
qPh2        0.0864  0.0114   0.0469  0.0470  94926 switches

Normal ending
