Genepop 4.7.0: Hardy-Weinberg test

File: pop8.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:18:49)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.0246  0.0044   0.0628  0.0629  94870 switches
qPh2        0.0434  0.0083   0.0578  0.0579  94898 switches

Normal ending
