Genepop 4.7.0: Hardy-Weinberg test

File: pop92.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:18:55)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.3545  0.0156   0.0145  0.0145  94935 switches
qPh2        0.1570  0.0163   0.0369  0.0369  94813 switches

Normal ending
