Genepop 4.7.0: Hardy-Weinberg test

File: pop94.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:18:55)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.3545  0.0159   0.0145  0.0145  94931 switches
qPh2        0.3681  0.0215   0.0155  0.0155  94819 switches

Normal ending
