Genepop 4.7.0: Hardy-Weinberg test

File: pop6.txt (Outputted by simuPOP at Tue, 17 Jul 2018 08:17:24)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.0000  0.0000   0.9859  0.9868  94945 switches
qPh2        0.0000  0.0000   0.9980  0.9990  94903 switches

Normal ending
