Genepop 4.7.0: Hardy-Weinberg test

File: pop28.txt (Outputted by simuPOP at Tue, 12 Jun 2018 12:59:27)

Number of populations detected:    1
Number of loci detected:           1


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-10000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.2759  0.0446   0.0050  0.0050  98569 switches

Normal ending
